#Database to generate typing
easy = ["Hi this is a writing test mate..we will evaluate your power to write through your keyword",
        "Always bear in mind that your own resolution to succeed is more important than any other.",
        "The best time to plant a tree was 20 years ago. The second best time is now.",
        "The beautiful butterflies danced gracefully among the blooming flowers in the bright summer sunshine.",
        "Once upon a time in a small, quiet village, there lived a kind old woman who loved baking cookies for her neighbors.",
        "The little boy ran quickly down the hill, laughing and shouting with joy as his kite soared high in the clear blue sky.",
        "On a warm and peaceful Sunday morning, the family decided to go for a picnic by the sparkling lake surrounded by tall, green trees.",
        "As the sun set behind the mountains, the sky turned shades of pink, orange, and purple, creating a magical scene that everyone admired.",
        "The curious cat wandered through the big, old house, exploring every room and jumping onto every piece of furniture it could find.",
        "Early in the morning, the farmer woke up, fed the chickens, milked the cows, and tended to the vegetable garden in the backyard.",
        "During the winter holidays, the children built a huge snowman, decorated it with a carrot nose, and gave it a big, friendly smile.",
        "After a long and exciting day at the amusement park, the tired family sat down together to eat a delicious dinner and share their favorite moments.",
        "The young girl loved reading stories about brave knights, magical lands, and daring adventures that took her imagination to incredible places."]

medium = ["There the matter ended and six months passed without any further notice 54 police has been arrested at 17th Street of Gujrat, they published stories or rumours.",
        "Cast iron stomach means Someone who has no problems, complications or ill effects with eating anything like eating 90 bananas and 70 pineapples at a strech",
        "My hotel room number is B203.",
        "The bus leaves at 7:45 AM from platform C12.",
        "His username is Alex99 on the website.",
        "The library code is A45-B67-C89.",
        "My friend's phone number is 123-456-7890.",
        "The flight number is AA307, departing at 14:30.",
        "The package tracking ID is TRK98273561.",
        """The quiz score was 85/100 in Class 10B. Her account number ends with 5678. The recipe calls for 2 cups of sugar and 3/4 cup of milk.""",
        """The team won the match by 3-2.The registration deadline is March 15th, 2025, at 11:59 PM.""",
        "The discount code SAVE10 gives you 10% off.",
        "My PIN is 4578, but I never write it down.",
        "The car's license plate reads ABC-1234."]

hard = ['The password is "P@ssw0rd123!" -> remember it carefully.',
        "My email is john.doe@example.com, please send the documents there.",
        "Call me at +1-800-555-1234 if you need help;",
        "The flight departs at 7:45 AM on 12/25/2025.",
        "She scored 95% in her final exams that's impressive!",
        "The file size is approximately 1.25 GB.",
        "Use \Ctrl+C to copy and \Ctrl+V to paste.",
        "The meeting is scheduled for 03:30 PM EST.",
        "To solve the equation: x^2 + 3x - 4 = 0, use the quadratic formula.",
        'The Wi-Fi password is "H0m3@2025".',
        'The password is Xy@!z9#3$7&bR4q.',
        "He calculated the value of e^(iπ) + 1 = 0.",
        "The event starts at 12:45 PM on 03/14/2025.",
        "My license plate is 4F7-X2P.",
        "To solve the equation, divide 24÷6+3x4=18.",
        "The code is #ABC123; use it for access.",
        "Temperature today: -5°C at 10:30 AM.",
        "The chemical formula for glucose is C6H12O6.",
        "Phone number: +1-800-555-0199, call after 6:00 PM.",
        "The Wi-Fi password is H0m3$w33tH0m3.",
        "The URL is https://www.example-site.com/path?query=123&lang=en.",
        "Remember the binary code: 1010110 0110100 1101101.",
        "The ISBN of the book is 978-3-16-148410-0.",
        "The Fibonacci sequence starts: 1, 1, 2, 3, 5, 8, 13...."]
